name: CI

 
on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      
      - name: Install 🔧
        run: npm install
      
      - name: unit-test
        run : npm run unit-tests
        
      - name: integration-test
        run : npm run integration-tests
      
      - name: Test Report unit
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: mocha Tests unit      
          path: ./test-results.json    
          reporter: mocha-json              
      
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'ms-starwars'
          path: '.'
          format: 'HTML'    
          others: ''
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Depcheck report
           path: ${{github.workspace}}/reports
           
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL }}
          SONAR_TOKEN: ${{ secrets.S15087 }}
        with:
          args: >
            -Dsonar.organization=s15087
            -Dsonar.projectKey=s15087_ms-starwars
          projectBaseDir: ./
          
      - name: Set up QEMU 🏗️
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx 🐋
        uses: docker/setup-buildx-action@v1
      
      - name: Login to JFrog 🐸  
        uses: docker/login-action@v1
        with:
          registry: wisit.jfrog.io
          username: ${{ secrets.JFROG_USERNAME }}
          password: ${{ secrets.JFROG_PASSWORD }}
      
      - name: Build and push 🐳
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wisit.jfrog.io/default-docker-local/test:latest
